#' Google Slides API
#' Reads and writes Google Slides presentations.
#'
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2023-02-11 20:37:07
#' filename: C:/Users/isaac/Documents/slides_api/googleslidesv1.auto/R/slides_functions.R
#' api_json: api_json
#'
#' @details
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/presentations
#' \item https://www.googleapis.com/auth/spreadsheets.readonly
#' \item https://www.googleapis.com/auth/spreadsheets
#' \item https://www.googleapis.com/auth/presentations.readonly
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.readonly
#' }
#'
#' @docType package
#' @name slides_googleAuthR
#'
NULL
## NULL



#' Gets the latest version of the specified presentation.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/slides/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.readonly
#' \item https://www.googleapis.com/auth/presentations
#' \item https://www.googleapis.com/auth/presentations.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/drive.readonly, https://www.googleapis.com/auth/presentations, https://www.googleapis.com/auth/presentations.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param presentationId The ID of the presentation to retrieve
#' @export
presentations.get <- function(presentationId) {
  request <- gargle::request_build(
    method = "GET",
    path = "/v1/presentations/{presentationId}",
    params = list(presentationId = presentationId),
    base_url = "https://slides.googleapis.com",
    token = gsd_token()
  )
  response <- request_make(request)
  response_process(response)
  # request
}

#' Applies one or more updates to the presentation. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and only the third one returns information. The response would have two empty replies: the reply to the third request, and another empty reply, in that order. Because other users may be editing the presentation, the presentation might not exactly reflect your changes: your changes may be altered with respect to collaborator changes. If there are no collaborators, the presentation should reflect your changes. In any case, the updates in your request are guaranteed to be applied together atomically.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/slides/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.readonly
#' \item https://www.googleapis.com/auth/presentations
#' \item https://www.googleapis.com/auth/spreadsheets
#' \item https://www.googleapis.com/auth/spreadsheets.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/drive.readonly, https://www.googleapis.com/auth/presentations, https://www.googleapis.com/auth/spreadsheets, https://www.googleapis.com/auth/spreadsheets.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param BatchUpdatePresentationRequest The \link{BatchUpdatePresentationRequest} object to pass to this method
#' @param presentationId The presentation to apply the updates to
#' @family BatchUpdatePresentationRequest functions
#' @export
presentations.batchUpdate <- function(BatchUpdatePresentationRequest, presentationId) {
  # stopifnot(inherits(BatchUpdatePresentationRequest, "gar_BatchUpdatePresentationRequest"))

  request <- gargle::request_build(
    method = "POST",
    path = "/v1/presentations/{presentationId}:batchUpdate",
    params = list(presentationId = presentationId),
    body = BatchUpdatePresentationRequest,
    base_url = "https://slides.googleapis.com",
    token = gsd_token()
  )
  response <- request_make(request)
  response_process(response)
}

#' Creates a blank presentation using the title given in the request.
#' If a `presentationId` is provided, it is used as the ID of the new
#' presentation. Otherwise, a new ID is generated. Other fields in the request,
#' including any provided content, are ignored. Returns the created presentation.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/slides/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/presentations
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/presentations)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Presentation The \link{Presentation} object to pass to this method
#' @family Presentation functions
#' @export
presentations.create <- function(Presentation) {
  request <- gargle::request_build(
    method = "POST",
    path = "/v1/presentations",
    body = Presentation,
    base_url = "https://slides.googleapis.com",
    token = gsd_token()
  )
  response <- request_make(request)
  response_process(response)
}




#' Gets the latest version of the specified page in the presentation.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/slides/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.readonly
#' \item https://www.googleapis.com/auth/presentations
#' \item https://www.googleapis.com/auth/presentations.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/drive.readonly, https://www.googleapis.com/auth/presentations, https://www.googleapis.com/auth/presentations.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param presentationId The ID of the presentation to retrieve
#' @param pageObjectId The object ID of the page to retrieve
#'
#' @importFrom gargle request_build request_make response_process
#' @export
presentations.pages.get <- function(presentationId, pageObjectId) {
  # url <- sprintf("https://slides.googleapis.com/v1/presentations/%s/pages/%s",
                 # presentationId, pageObjectId)
  # slides.presentations.pages.get
  # f <- googleAuthR::gar_api_generator(url, "GET", data_parse_function = function(x) x)
  # f()
  request <- gargle::request_build(
    method = "GET",
    path = "/v1/presentations/{presentationId}/pages/{pageObjectId}",
    params = list(presentationId = presentationId, pageObjectId = pageObjectId),
    base_url = "https://slides.googleapis.com",
    token = gsd_token()
  )
  response <- request_make(request)
  response_process(response)
}


#' Generates a thumbnail of the latest version of the specified page in the presentation and returns a URL to the thumbnail image. This request counts as an [expensive read request](/slides/limits) for quota purposes.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/slides/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.readonly
#' \item https://www.googleapis.com/auth/presentations
#' \item https://www.googleapis.com/auth/presentations.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/drive.readonly, https://www.googleapis.com/auth/presentations, https://www.googleapis.com/auth/presentations.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param presentationId The ID of the presentation to retrieve

#' @param pageObjectId The object ID of the page whose thumbnail to retrieve

#' @param thumbnailProperties.thumbnailSize The optional thumbnail image size

#' @param thumbnailProperties.mimeType The optional mime type of the thumbnail image
#'
#' @export


presentations.pages.getThumbnail <- function(presentationId,
                                             pageObjectId,
                                             thumbnailProperties.thumbnailSize = NULL,
                                             thumbnailProperties.mimeType = NULL) {


  query_params = rm_null_objs(list(
    thumbnailProperties.thumbnailSize = thumbnailProperties.thumbnailSize,
    thumbnailProperties.mimeType = thumbnailProperties.mimeType
    ))

  request <- gargle::request_build(
    method = "GET",
    path = "/v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
    params = c(
      list(presentationId = presentationId, pageObjectId = pageObjectId),
      query_params
    ),
    base_url = "https://slides.googleapis.com",
    token = gsd_token()
  )
  response <- request_make(request)
  response_process(response)
}



